# Generated by Django 4.2.4 on 2023-09-02 06:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_email_post_published_post_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('WB', 'Web Developments'), ('DB', 'Desktop Developments')], default='WB', max_length=30),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
