# Generated by Django 4.2.4 on 2023-09-02 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_category_alter_post_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('WB', 'Web Developments'), ('DB', 'Desktop Developments'), ('DS', 'Data Science')], default='WB', max_length=30),
        ),
    ]
